CREATE SCHEMA IF NOT EXISTS university;
USE university;

CREATE TABLE IF NOT EXISTS students(
	id INT PRIMARY KEY AUTO_INCREMENT,
	firstname VARCHAR(45) NOT NULL,
    lastname VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS courses(
	id INT PRIMARY KEY AUTO_INCREMENT,
	course_name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS enrols(
	student_id INT NOT NULL,
	course_id VARCHAR(45) NOT NULL,
    grade FLOAT NOT NULL
);